-- Insertando algunos registros para que la BBDD no esté vacía

INSERT INTO JUGADORES (ID,USERNAME,PASSWORD,ID_PERSONAJE) VALUES (001,'Alex','pass123',1002);
INSERT INTO JUGADORES (ID,USERNAME,PASSWORD,ID_PERSONAJE) VALUES (002,'Mario','pass456',0);
INSERT INTO JUGADORES (ID,USERNAME,PASSWORD,ID_PERSONAJE) VALUES (003,'Lucia','pass666',1001);
INSERT INTO JUGADORES (ID,USERNAME,PASSWORD,ID_PERSONAJE) VALUES (004,'Pablo','pass999',1003);
INSERT INTO JUGADORES (ID,USERNAME,PASSWORD,ID_PERSONAJE) VALUES (005,'Alicia','pass000',0);

INSERT INTO PERSONAJES (ID,NAME,RAZA,OFICIO) VALUES (1001,'Eldergos','Elfo','Arquero');
INSERT INTO PERSONAJES (ID,NAME,RAZA,OFICIO) VALUES (1002,'Kur Hag','Orco','Herrero');
INSERT INTO PERSONAJES (ID,NAME,RAZA,OFICIO) VALUES (1003,'Lionde','Humano','Bardo');
INSERT INTO PERSONAJES (ID,NAME,RAZA,OFICIO) VALUES (1004,'Lionds','Humano','Mercader');