-- SCHEMA

DROP TABLE IF EXISTS JUGADORES;
DROP TABLE IF EXISTS PERSONAJES;

CREATE TABLE JUGADORES (
    ID INTEGER IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_PERSONAJE INTEGER
);

CREATE TABLE PERSONAJES (
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    RAZA VARCHAR(255) NOT NULL,
    OFICIO VARCHAR(255) NOT NULL
);